chunk_size: 100000
db_user: changeme
db_password: changeme
db_host: changeme
db_port: changeme
db_name: changeme
tables:
    - name: changeme
      columns: []
      output_dir: data_dumps/
    - name: changeme
      columns: []
      output_dir: data_dumps/